name: MysticSurvival
author: QuickScythe
version: ALPHA
description: The MysticCloud Survival plugin.
api-version: 1.15
main: net.mysticcloud.spigot.spigot.MysticSurvival
commands:
  warp:
    usage: /warp [type|default=warp] <name> [selector]
    description: Teleport to a location
  addwarp:
    aliases: ['createwarp']
    usage: /addwarp [type|default=warp] <name>
    description: Add a warp to the database
  removewarp:
    aliases: ['deletewarp']
    usage: /deletewarp [type|default=warp] <name>
    description: remove a warp from the database